config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  get 'home', to: 'home#index'
  get 'user', to: 'users#show'

  resources :categories

  resources :quizzes do
    member do
      post :start
    end
    resources :quiz_comments, only: %i[create destroy], shallow: true
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
  end

  resources :quiz_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :rooms
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quiz, only: [:show, :edit, :update, :destroy, :start]

  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz_comment = QuizComment.new
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user = current_user

    if @quiz.save
      redirect_to quizzes_path, notice: "Quiz: #{@quiz.title} was successfully created!"
    else
      render :new, alert: "An error occured while saving a quiz."
    end
  end

  def edit
  end

  def update
    if @quiz.update(quiz_params)
      redirect_to @quiz, notice: "Quiz: #{@quiz.title} was successfully updated!"
    else
      redirect_to :edit, alert: "An error occurred while editing a quiz."
    end
  end

  def destroy
    @quiz.destroy
    redirect_to quizzes_path, notice: "Quiz was successfully deleted."
  end

  def start
    redirect_to QuizPassage.create(user_id: current_user.id, quiz_id: @quiz.id)
  end

  private

  def set_quiz
    @quiz = Quiz.find(params[:id])
  end

  def quiz_params
    params.require(:quiz).permit(:title, :category_id, :level, :room_id)
  end
end

app/views/quizzes/_form.html.slim
.row.mt-3
	.col.col-md-4
		.card.border-primary
			.card-body
				= form_for([@quiz]) do |form|
					= render 'shared/errors', resource: @quiz

					.form-group.m-2
						= form.label(:title, class: 'm-2')
						= form.text_field(:title, class: 'm-2', placeholder: 'Some title')
						br

            = form.label(:level, class: 'm-2')
            = form.select(:level, 1..10, class: 'm-2', propmt: 'Some title')
            br

            = form.label(:category, class: 'm-2')
            = form.collection_select(:category_id, Category.all,
                    :id, :title, prompt: 'Select category', class: 'm-2')
            br

						= form.submit('Create', class: 'btn btn-primary m-2')

app/views/quizzes/_quiz.html.slim
.li
	= link_to quiz.title, quiz_path(quiz), class: 'm-2'

	- if quiz.ready?
		= link_to 'Start', start_quiz_path(quiz), method: :post, class: 'm-2 btn btn-primary'
	- else
		| Quiz is not ready

app/views/quizzes/edit.html.slim
h1
| Edit #{@quiz.title}

= render 'form'

app/views/quizzes/index.html.slim
- if @quizzes.any?
    h2 All Quizzes:
	.ul.p-2
		= render @quizzes
- else
	h2 There are no quizzes
hr


= link_to 'New Quiz', new_quiz_path

app/views/quizzes/new.html.slim
h1 Create new quiz

= render 'form'

app/views/quizzes/show.html.slim
h1 =@quiz.title
h3
  | Category: #{link_to @quiz.category.title, category_path(@quiz.category)}
h3
  | Author: #{@quiz.user.email}


- if @quiz.questions.any?
  h3 Questions:
  ul
    = render @quiz.questions
- else
  h3 There are no questions for this Quiz

p
	| Ready? #{@quiz.ready?}

= link_to 'New question', new_quiz_question_path(@quiz), class: 'm-2'
= link_to 'Edit', edit_quiz_path(@quiz), class: 'm-2'
= link_to 'Destroy', quiz_path(@quiz), method: :delete, class: 'm-2'

- if @quiz.quiz_comments.any?
  h3 Comments:
  ul
    = render @quiz.quiz_comments
/ - else
/   h3 There are no comments for this Quiz

.quiz-comment-errors
  =render 'shared/errors', resource: @quiz_comment
h5 Write comment
= form_with model: [@quiz, @quiz_comment], 
						url: quiz_quiz_comments_path(@quiz.id), 
					  mehtod: :post, local: false, 
					  class: 'm-2', id: 'comment-form' do |f|
	= f.label :body
	= f.text_area :body, rows: 4, cols: 4, class: 'form-control'

	= f.submit 'Post', class: 'm-2 btn btn-primary'