config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  get 'home', to: 'home#index'
  get 'user', to: 'users#show'

  resources :categories

  resources :quizzes do
    member do
      post :start
    end
    resources :quiz_comments, only: %i[create destroy], shallow: true
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
  end

  resources :quiz_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :rooms
end

app/views/shared/_errors.html.slim
- if resource&.errors.present? 
  = content_tag :div, class: "resource-errors", data: { resource_id: resource.id }  do 
    .ul
      - resource.errors.full_messages.each do |message|
        .li
        	= message

app/views/shared/_flash.html.slim
- flash.each do |key, message| 
	= content_tag :p, message, class: message_class(key)

app/views/shared/_header.html.slim
nav.navbar.navbar-light.bg-light

  nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .container-fluid
      = link_to 'Quiz Pleaze?', root_path, class: "navbar-brand"
    ul.navbar-nav
      li.nav-item
        = link_to 'Categories', categories_path, class: "nav-link actives"
      li.nav-item
        = link_to 'Quizzes', quizzes_path, class: "nav-link actives"
      li.nav-item
        = link_to 'Rooms', rooms_path, class: "nav-link actives"

  form.d-flex

    - if user_signed_in?
      = link_to current_user.email, user_path, class: "btn"
      = link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn"
    - else
      = link_to 'Login', new_user_session_path, class: "btn"
      = link_to 'Register', new_user_registration_path, class: "btn"