config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  get 'home', to: 'home#index'
  get 'user', to: 'users#show'

  resources :categories

  resources :quizzes do
    member do
      post :start
    end
    resources :quiz_comments, only: %i[create destroy], shallow: true
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
  end

  resources :quiz_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :rooms
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: %i[show destroy edit update]
  before_action :set_question, only: %i[create new]

  def show
    @question = @answer.question
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to answer_path(@answer)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      redirect_to answer_path(@answer)
    else
      render :new
    end
  end

  def destroy
    question = @answer.question
    @answer.destroy
    redirect_to question
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/views/answers/_answer.html.slim
li
  = link_to answer.body, answer_path(answer), class: 'm-1'
  = link_to 'Edit', edit_answer_path(answer), class: 'm-1'
  = link_to 'Destroy', answer_path(answer), method: :delete, class: 'm-1'

app/views/answers/_form.html.slim
.row.mt-3
	.col.col-md-4
		.card.border-primary
			.card-body
				= form_for([@question, @answer]) do |form|
					= render 'shared/errors', resource: @answer

					.form-group.m-2
						= form.label(:body, class: 'm-2')
                        br
						= form.text_area(:body, class: 'm-2 form-control',
                                        placeholder: "Answer's body", rows: 4, cols:4)


                        = form.label(:correct, class: 'm-2')
                        = form.check_box(:correct, class: 'm-2')
                        br

						= form.submit('Submit', class: 'btn btn-primary m-2')

app/views/answers/edit.html.slim
h1
| Edit #{@answer.body}

= render 'form'

app/views/answers/new.html.slim
h1 Create new answer

= render 'form'

app/views/answers/show.html.slim
h3
  | Answer: #{@answer.body}
h1
  | Answer for question  #{link_to @question.title, question_path(@question)}


= link_to 'New answer', new_question_answer_path(@question)
br
= link_to 'Edit', edit_answer_path(@answer)
br
= link_to 'Destroy', answer_path(@answer), method: :delete