config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users

  get 'home', to: 'home#index'
  get 'user', to: 'users#show'

  resources :categories

  resources :quizzes do
    member do
      post :start
    end
    resources :quiz_comments, only: %i[create destroy], shallow: true
    resources :questions, shallow: true do
      resources :answers, shallow: true
    end
  end

  resources :quiz_passages, only: %i[show update] do
    member do
      get :result
    end
  end

  resources :rooms
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :quizzes, dependent: :nullify

  validates :title, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: "Category: #{@category.title} was successfully created!"
    else
      render :new, alert: "An error occurred while saving a category."
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: "Category: #{@category.title} was successfully updated!"
    else
      redirect_to :edit, alert: "An error occurred while editing a category."
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: "Category was successfully deleted."
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/views/categories/_category.html.slim
.li
	= link_to category.title, category_path(category)

app/views/categories/_form.html.slim
.row.mt-3
	.col.col-md-4
		.card.border-primary
			.card-body
				= form_for([@category]) do |form|
					= render 'shared/errors', resource: @category

					.form-group.m-2
						= form.label(:title, class: 'm-2')
						= form.text_field(:title, class: 'm-2', placeholder: 'Some title')
						br		
						= form.submit('Create', class: 'btn btn-primary m-2')

app/views/categories/edit.html.slim
h1
| Edit #{@category.title}

= render 'form'

app/views/categories/index.html.slim
- if @categories.any?
    h2 All Categories:
	.ul.p-2
		= render @categories
- else
	h2 There are no categories
hr


= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 Create new category

= render 'form'

app/views/categories/show.html.slim
h1 =@category.title

- if @category.quizzes.any?
  h3 Tests
  ul
    .card.border-primary.p-2
      = render @category.quizzes
- else
  h3 There are no quizzes with such category

= link_to 'Edit', edit_category_path(@category)
br

= link_to 'Destroy', category_path(@category), method: :delete